/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Dao.ProductDAO;
import Models.Entities.Product;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import Controllers.CartController;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author Usuario
 */
public class Products extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Products.class.getName());
    
    // Conectamos el carrito de tus compañeros
    private CartController miCarrito = new CartController();

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar al Carrito");

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNombre.setText("Nombre Hamburguesa");

        lblDescripcion.setText("Ingredientes");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPrecio.setText("$0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar))
        );

        jScrollPane1.setViewportView(panelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Products().setVisible(true));
    }
public void cargarProductos() {
        // Limpiamos tu panel contenedor grande
        panelContenedor.removeAll();
        jPanel1.setVisible(false);

        // Llamamos al código que hiciste en VS Code
        ProductDAO dao = new ProductDAO();
        List<Product> lista = dao.findAll(); 

        for (Product prod : lista) {
            // Creamos una tarjetita nueva por cada producto
            JPanel tarjeta = new JPanel();
            tarjeta.setPreferredSize(new Dimension(200, 280));
            tarjeta.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));
            tarjeta.setLayout(null);

            // --- SECCIÓN DE LA FOTO INTELIGENTE ---
            JLabel lblF = new JLabel("", SwingConstants.CENTER);
            lblF.setBounds(10, 10, 180, 120);
            lblF.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            
            String rutaImagenBase = "src/images/"; 
            String nombreImagenDB = prod.getImagePath(); 

            if (nombreImagenDB != null && !nombreImagenDB.isEmpty()) {
                String rutaCompleta = rutaImagenBase + nombreImagenDB;
                File archivoFoto = new File(rutaCompleta);

                if (archivoFoto.exists()) {
                    try {
                        ImageIcon iconOriginal = new ImageIcon(rutaCompleta);
                        Image imgEscalada = iconOriginal.getImage().getScaledInstance(lblF.getWidth(), lblF.getHeight(), Image.SCALE_SMOOTH);
                        lblF.setIcon(new ImageIcon(imgEscalada));
                    } catch (Exception e) {
                        lblF.setText("Error Imagen");
                        lblF.setForeground(Color.RED);
                    }
                } else {
                    lblF.setText("<html><center>FOTO NO<br>ENCONTRADA</center></html>");
                    lblF.setForeground(Color.GRAY);
                    lblF.setBackground(new Color(240, 240, 240)); 
                    lblF.setOpaque(true);
                }
            } else {
                lblF.setText("Sin Foto");
                lblF.setForeground(Color.LIGHT_GRAY);
                lblF.setBackground(new Color(240, 240, 240));
                lblF.setOpaque(true);
            }
            tarjeta.add(lblF);

            // Nombre
            JLabel lblN = new JLabel(prod.getName());
            lblN.setBounds(10, 140, 180, 20);
            lblN.setFont(new Font("Tahoma", Font.BOLD, 14));
            tarjeta.add(lblN);

            // Descripción
            JLabel lblD = new JLabel("<html>" + prod.getDescription() + "</html>");
            lblD.setBounds(10, 160, 180, 40);
            tarjeta.add(lblD);

            // Precio
            JLabel lblP = new JLabel("$" + prod.getPrice());
            lblP.setBounds(10, 210, 180, 20);
            lblP.setFont(new Font("Tahoma", Font.BOLD, 16));
            tarjeta.add(lblP);

            // Botón conectado al carrito
           // --- BOTÓN CARRITO ---
            JButton btnA = new JButton("Agregar al Carrito");
            btnA.setBounds(10, 240, 180, 30);
            
            btnA.addActionListener(e -> {
                miCarrito.addProduct(prod, 1);
                
                // Imprimimos el resumen detallado en la consola
                System.out.println("----- RESUMEN DE CARRITO -----");
                System.out.println("Agregaste: " + prod.getName() + " ($" + prod.getPrice() + ")");
                System.out.println("Total de productos en carrito: " + miCarrito.getItemCount());
                System.out.println("Valor total: $" + miCarrito.calculateTotal());
                System.out.println("------------------------------\n"); // \n es para dejar un renglón en blanco
            });
            
            tarjeta.add(btnA);
            panelContenedor.add(tarjeta);
        }

        // Actualizamos la pantalla
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
