
#Pone al final de la ruta, el nombre de la Base de Datos que armaste
b.url=db.url=jdbc:mysql://localhost:3306/basededatos123

#pone aca tu usuario de la Base de Datos
db.user= abc
#pone aca tu contraseña de la Base de Datos
db.password=123