
#Pone al final de la ruta, el nombre de la Base de Datos que armaste
db.url=jdbc:mysql://localhost:3306/burger_system

#pone aca tu usuario de la Base de Datos
db.user= root
#pone aca tu contrase\u00c3\u00b1a de la Base de Datos
db.password=root